from __future__ import annotations

from src.eda import actions, data, diagnostics, modeling, visualized

from src.eda.actions import (
    build_action_plan,
    build_executive_summary,
    build_self_scoring,
    simulate_action_roi,
)
from src.eda.data import (
    build_descriptive_scorecard,
    build_descriptive_summary,
    build_dimension_mix,
    build_fact_tables,
    build_geography_snapshot,
    build_monthly_kpis,
    build_quality_audit,
    build_quarterly_kpis,
    build_relation_summary,
    build_waterfall_summary,
    load_data,
    preview_table_bundle,
    reconcile_with_sales,
    set_plot_theme,
)
from src.eda.diagnostics import (
    build_cancellation_diagnostic,
    build_cancellation_story,
    build_delivery_diagnostics,
    build_excluded_driver_appendix,
    build_promo_proxy,
    build_promo_story,
    build_root_cause_summary,
    build_size_diagnostic,
    build_size_story,
    build_stockout_proxy,
    build_story_root_causes,
)
from src.eda.modeling import (
    build_model_dataset,
    build_model_interpretation,
    build_review_queue_summary,
    build_risk_segments,
    evaluate_predictions,
    fit_models,
    split_model_data,
)
from src.eda.visualized import (
    plot_action_matrix,
    plot_cancellation_diagnostic,
    plot_cancellation_story,
    plot_delivery_diagnostics,
    plot_descriptive_scorecard,
    plot_geography_snapshot,
    plot_kpi_trends,
    plot_mix_dashboard,
    plot_model_diagnostics,
    plot_promo_proxy,
    plot_promo_story,
    plot_review_capture,
    plot_risk_segments,
    plot_sales_reconciliation,
    plot_size_heatmap,
    plot_size_story,
    plot_stockout_proxy,
    plot_waterfall,
)

__all__ = [
    # Re-exported submodules (optional access)
    "actions",
    "data",
    "diagnostics",
    "modeling",
    "visualized",
    # Facade builders (actions)
    "build_action_plan",
    "build_executive_summary",
    "build_self_scoring",
    "simulate_action_roi",
    # Facade builders (data)
    "build_descriptive_scorecard",
    "build_descriptive_summary",
    "build_dimension_mix",
    "build_fact_tables",
    "build_geography_snapshot",
    "build_monthly_kpis",
    "build_quality_audit",
    "build_quarterly_kpis",
    "build_relation_summary",
    "build_waterfall_summary",
    "load_data",
    "preview_table_bundle",
    "reconcile_with_sales",
    "set_plot_theme",
    # Facade builders (diagnostics)
    "build_cancellation_diagnostic",
    "build_cancellation_story",
    "build_delivery_diagnostics",
    "build_excluded_driver_appendix",
    "build_promo_proxy",
    "build_promo_story",
    "build_root_cause_summary",
    "build_size_diagnostic",
    "build_size_story",
    "build_stockout_proxy",
    "build_story_root_causes",
    # Facade builders (modeling)
    "build_model_dataset",
    "build_model_interpretation",
    "build_review_queue_summary",
    "build_risk_segments",
    "evaluate_predictions",
    "fit_models",
    "split_model_data",
    # Facade plots (visualized)
    "plot_action_matrix",
    "plot_cancellation_diagnostic",
    "plot_cancellation_story",
    "plot_delivery_diagnostics",
    "plot_descriptive_scorecard",
    "plot_geography_snapshot",
    "plot_kpi_trends",
    "plot_mix_dashboard",
    "plot_model_diagnostics",
    "plot_promo_proxy",
    "plot_promo_story",
    "plot_review_capture",
    "plot_risk_segments",
    "plot_sales_reconciliation",
    "plot_size_heatmap",
    "plot_size_story",
    "plot_stockout_proxy",
    "plot_waterfall",
]
